name: V2RayXS build actions

on:
  push:
    branches:
      - master
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-all:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Init
        run: git submodule init && git submodule update
      - name: Download xray-core
        run: |
          export SRCROOT=$(pwd)
          export ARCHS=x86_64
          bash V2RayX/dlcorex.sh
      - name: Download geo data
        run: |
          export SRCROOT=$(pwd)
          bash V2RayX/dlgeodat.sh
      - name: Build V2RayXS for x86_64 Arch
        run: /usr/bin/env bash build.sh x86_64
      - name: Build V2RayXS for arm64 Arch
        run: /usr/bin/env bash build.sh arm64
      - name: Uploading assets...
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref }}
          body: "- TODO New Release.\n\nUpdate: 00/00/00\n\nThanks again to the contributors. ðŸŒˆ\nlight up the star to let me know you are using it. ðŸ’«\nthank you for your support."
          draft: true
          prerelease: true
          append_body: true
          files: |
            build/out/V2RayXS_x86_64.app.zip
            build/out/V2RayXS_x86_64.app.zip.dgst
            build/out/V2RayXS_arm64.app.zip
            build/out/V2RayXS_arm64.app.zip.dgst
